name = "OrangechinSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acd345639d5291c19eab0c9d842c5117a741ffd5a96a4186cce11eec78182d2a"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
