name = "OrangechinSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54c14e40741b21983e96106a932d1318c276bb27c1fddb639cf078bda3937c47"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
