name = "OrangechinSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "787e302ce600149e5aea859808c49f1de27905ffca1412117ecfe1a72378c2a7"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
