name = "OrangechinSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd8dd21f13fddcd7e8f7a9db7313d0a2ff1ae615c682d87962192ec7a3eb8b27"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
