name = "OrangechinSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8092d16f6046f98dfad172ff261d0be9c937d63c7f3220696e5e1a60f6e58ea4"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
