name = "Orangechin finality"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "372a7cd776c18efccca306490c991cfdf606f58c142212422817fdb5fa280f22"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
