name = "OrangechinSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df59deae463d096a04fb653c6e18b1590cd6552ff676aa53673bb317ab8cb036"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
