name = "OrangechinSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d55c9d5a258e1a1cecda517507640a83e3fb67a71c74d04d8f9a37d3e94f9a0e"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
