name = "OrangechinSMP"
author = "Hell0HD"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71c670afacadec69ef372f959f6e09731d50ca7c71172c1df4d1e11de5fd9e13"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
