name = "OrangechinSMP"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7e3b93123bd87b74557040d139553530785aac0ae0dbfb55e2e7020f3c4a868"

[versions]
minecraft = "1.20.1"
quilt = "0.26.0"
